server.port=${PORT:8082}
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=eventdb
faculty.service.url=${FACULTY_SERVICE_URL}
spring.jackson.serialization.write-dates-as-timestamps=false